name: CI Pipeline

on:
  push:
    branches: [main, dev, develop, amit]
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Linter
        run: echo "Linting code..."

  build-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install Dependencies
        run: npm ci
      # - name: Run Node Tests
      #   run: npm test

  test:
    runs-on: ubuntu-latest
    needs: [build-node]
    steps:
      - uses: actions/checkout@v3
      - name: Run Tests
        run: echo "Running tests..."

  deploy-dev:
    runs-on: ubuntu-latest
    needs: [test]
    if: github.ref == 'refs/heads/dev'
    environment: dev
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Dev
        run: |
          echo "Deploying to Dev environment..."
          # e.g. docker build -t myapp:dev .
          # docker push myregistry/myapp:dev
          # kubectl apply -f k8s/dev/

  deploy-qa:
    runs-on: ubuntu-latest
    needs: [test]
    if: github.ref == 'refs/heads/main'
    environment: qa
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to QA
        run: |
          echo "Deploying to QA environment..."
          # e.g. docker build -t myapp:qa .
          # docker push myregistry/myapp:qa
          # kubectl apply -f k8s/qa/
